---

-
  stat:
    path: ~/.bash_profile
  register: bash_file

-
  name: Create user bash file
  file:
    path: ~/.bash_profile
    state: touch
  when: bash_file.stat.exists == False

-
  name: Configure bash profile language encoding
  lineinfile:
    dest: ~/.bash_profile
    line: "export LANG={{ buildfarm_lang_env_var }}"

-
  name: Configure profile file
  lineinfile:
    dest: ~/.profile
    line: "source ~/.bash_profile"
