---

-
  name: Install gem packages
  shell: "gem install --no-ri --no-rdoc {{item.name}} -v {{ item.version | default('\"\"') }}"
  args:
    executable: /bin/bash
  with_items: "{{ gem_packages }}"
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"
  become: yes
