- include: configure_node_env_vars.yml

-
  name: Update Cocoapods
  shell: bash -lc "pod repo update"
  register: pod_repo_update
  changed_when: pod_repo_update.stdout.find('Already up-to-date') == -1
  environment:
    PATH: "{{ buildfarm_env_path.stdout }}"
    GEM_HOME: "{{ buildfarm_env_gem.stdout }}"
    LANG: "{{ buildfarm_lang_env_var.stdout }}"
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"
